name: CI/CD to Heroku

on:
  push:
    branches:
      - main  # This can be any branch you want to trigger the workflow
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, mysqli, pdo_mysql

    # Step 3: Install Composer dependencies
    - name: Install dependencies
      run: composer install

    # Step 4: Deploy to Heroku using Heroku API
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main -f
